config/routes.rb
PlaylisterApp::Application.routes.draw do
  resources :genres

  resources :artists

  resources :songs

  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :song_genres
  has_many :songs, :through => :song_genres

  def self.find_or_create_by_csv_string(csv_string)
    genre_names = csv_string.split(",").collect{|g| g.strip.downcase}
    genre_names.collect do |genre_name|
      Genre.find_or_create_by(:name => genre_name)
    end
  end
  
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist

  has_many :song_genres
  has_many :genres, :through => :song_genres

  def artist_name=(artist_name)
    # Deprecated
    # self.artist = Artist.find_or_create_by_name(artist_name)
    
    # Avi likes these two
    self.artist = Artist.find_or_create_by(:name => artist_name)

    # Avi Doesn't Like This
    # self.artist = Artist.where(:name => artist_name).first_or_create
  end

  def genre_names=(csv_genre_names)
    Genre.find_or_create_by_csv_string(csv_genre_names).each do |genre|
      self.add_genre(genre)
    end
  end

  def add_genre(genre)
    self.song_genres.build(:genre => genre)
  end
end

app/models/song_genre.rb
class SongGenre < ActiveRecord::Base
  belongs_to :song
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render action: 'show', status: :created, location: @genre }
      else
        format.html { render action: 'new' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist_name,:genre_names)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1>Listing genres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Genre Name:</strong>
  <%= @genre.name %>
</p>

<br>
<h3>Songs:</h3>
<ul>
<% @genre.songs.each do |song| %>
    <p>
      <strong>Song Name:</strong>
      <%= song.name %>
    </p>

    <p>
      <strong>Artist Name:</strong>
      <%= link_to song.artist.name, song.artist if song.artist %>
    </p>
    <br>
  <%= end %>
</ul>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaylisterApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>Menu</p>
<ul>
  <li>
    <%= link_to 'Songs', songs_path %>
  </li>
  <li>
    <%= link_to 'Genres', genres_path %>
  </li>
  <li>
   <%= link_to 'Artists', artists_path %>
  </li>
</ul>

<%= yield %>

</body>
</html>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= form_for(@song) do |form_builder| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <label for="song_artist_name">Artist Name</label><br>
    <input type="text" name="song[artist_name]" id="song_artist_name">
  </div>

  <div class="field">
    <label for="song_artist_name">Comma Separated Genres</label><br>
    <input type="text" name="song[genre_names]" id="song_genre_names">
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= form_for(@song) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <label for="song_artist_name">Artist Name</label><br>
    <input type="text" name="song[artist_name]" id="song_artist_name">
  </div>

  <div class="field">
    <label for="song_artist_name">Comma Separated Genres</label><br>
    <input type="text" name="song[genre_names]" id="song_genre_names">
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist Name:</strong>
  <%= link_to @song.artist.name, @song.artist if @song.artist %>
</p>
<br>


<p>
  <strong>Genres:</strong>
  <%= @song.genres.collect{|g| g.name}.to_sentence %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>